### PR TITLE
Player error handling

### LINKED ISSUE #32: DBus connection error handling
Errors with the underlying connection to DBus may happen asynchonously. Establishing the connection and exporting the name on the bus is async and may fail after the constructor returns the player.

* connection to dbus cannot be established
* the name cannot be exported
* dbus connection is closed after connection is established

Error handling should be for debug logging to explain what happened and also give the user an option to retry the connection.

Best solution is probably to have an error event on the player with the original error and a message of what went wrong.

```js
player.on('error', (err, message) => { /* handle error */ })
```

Maybe give a hint to whether the player is connected after the error with a player property.

We can proxy the dbus-next connection error events into this when they happen.

### PR DESCRIPTION
**Pull request by acrisci**
Add an `error` event to the Player so users can handle DBus connection
errors. Proxy dbus connection and export errors through this event.

Update dbus-next to 0.4 and use the new interface export api.

Update tests for the new features and add a `ping` fixture.

fixes #32

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -173,11 +177,16 @@ function Player(opts) {
...
 
 Player.prototype.init = function(opts) {
+  let that = this;
   this.serviceName = `org.mpris.MediaPlayer2.${this.name}`;
   dbus.validators.assertBusNameValid(this.serviceName);
 
   this._bus = dbus.sessionBus();
 
+  this._bus.connection.on('error', (err) => {
+    that.emit('error', err);
```
Comment (emersion) [inline src/index.js]: No need for this, arrow functions don't shallow `this`

Comment (emersion) [reply src/index.js]: Or should I say, no need for _that_

Comment (acrisci) [reply src/index.js]: :+1:

**Comment by acrisci** [comment]
I think this is good to go.

I'm finding some of the test flakiness are actually dbus-next bugs that I'm fixing now.

**Comment by emersion** [comment]
Thanks!
